festjanta/FestJanta/urls.py
from django.conf.urls import patterns, include, url
from fest.views import *
from django.views.generic import TemplateView
from django.conf import settings
import os
from django.views.decorators.cache import cache_page
site_media = os.path.join(
	os.path.dirname(__file__), 'site_media'
)

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    #Home page
	url(r'^$', main_page),

    #account settings
    url(r'^settings/profile/$', profile_settings), 
    url(r'^settings/password/$', password_settings),
    url(r'^settings/college/(?P<college_slug>[^\s]+)/$', college_settings),
    url(r'^settings/fest/(?P<fest_slug>[^\s]+)/$', fest_settings), 
    url(r'^settings/$', user_settings),
    url(r'^edit-description/(?P<value>(\d))/(?P<vid>(\d+))/$', edit_description), #edit account settings

    #account login and registration
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', confirm), #activation link
	url(r'^login/$', remember_me_login), #login view
    url(r'^reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
            reset_confirm, name='password_reset_confirm'), #forgot password reset link
    url(r'^reset/$', reset, name='reset'), #get email for forgotten password reset
    url(r'^resetdone/$', 
        'django.contrib.auth.views.password_reset_done'), #email sent for recovery
	url(r'^logout/$', logout_page), #logout from account
    url(r'^register/$', register_page), #Signup for an account
    url(r'^register/success/$', TemplateView.as_view(template_name =  'registration/register_success.html')), #Signup success message
    url(r'^get-description/$', get_description), #Check if an email is registered already or username already exists

    #ajax autocomplete requests
    url(r'^ajax/college/autocomplete/$', ajax_college_autocomplete),
    url(r'^ajax/fest/autocomplete/$', ajax_fest_autocomplete),
    url(r'^query_suggestions/$', query_suggestions), #search bar

    #Fest and college management
    url(r'^save/$', fest_save_page), #add a fest and a college

    #Ajax updating of pages
    url(r'^post-comments/(?P<event_id>(\d+))/$', post_comments), #Post a comment and put it in latest comment
    url(r'^follows/(?P<fest_id>(\d+))/$', user_follows), #(Post) Follow a fest
    url(r'^unfollows/(?P<fest_id>(\d+))/$', user_unfollows), #(Post) Unfollow a fest
    url(r'^followscollege/(?P<college_id>(\d+))/$', user_follows_college), #(Post) Follow a college
    url(r'^unfollowscollege/(?P<college_id>(\d+))/$', user_unfollows_college), #(Post) Follow a college   
    url(r'^followsuser/(?P<user_id>(\d+))/$', follow), #(Post) Follow a user
    url(r'^unfollowsuser/(?P<user_id>(\d+))/$', unfollow), #(Post) Unfollow a user
    url(r'^like-event/(?P<vid>(\d+))/(?P<event_id>(\d+))/$', like_event), #(Post) Like an event
    url(r'^dislike-event/(?P<vid>(\d+))/(?P<event_id>(\d+))/$', dislike_event), #(Post) Dislike an event
    url(r'^get-complete/(?P<event_id>(\d+))/$', event_detail), #Load an event's complete detail
    url(r'^upload-image/(?P<vid>(\d+))/$', upload_image), # (Post) Upload DP
    url(r'^uploaded-image/$', get_uploaded_image), # (Get) Get uploaded user, college or fest dp
    url(r'^upload-event-album/$', upload_event_album), # (Post) Upload an album image
    url(r'^uploaded-event-image/$', uploaded_event_image), #(GET) Get thumbnail of an image uploaded in an album 
    url(r'^uploaded-event-album/(?P<event_id>(\d+))/$', uploaded_event_album), # (GET) Get an album and put it in latest event
    url(r'^delete-event/(?P<event_id>(\d+))/$', delete_event), # (Post) Delete an event

    url(r'^admin/', include(admin.site.urls)),

    # College/fest specific pages
    # Fest pages
    url(r'^fest/(?P<fest_slug>[^\s]+)/followers/$', fest_followers, name='fest_followers'),# List of followers of a fest
    url(r'^fest/(?P<fest_slug>[^\s]+)/post/(?P<event_id>(\d+))/$', event_page, name="event_page"), # Shows a single event a fest
    url(r'^fest/(?P<fest_slug>[^\s]+)/$', fest_page, name="fest_page"), # Fest page

    # College pages
    url(r'^college/(?P<college_slug>[^\s]+)/followers/$', college_followers, 
                                                          name='college_followers'), # List of followers of a college
    url(r'^college/(?P<slug>[^\s]+)/$', college_page), # College page

    # Info Pages
    url(r'^about/$', about), #about page
    url(r'^feedback/$', feedback), #(POST)feedback/contact page

    # Site media
	url(r'^site-media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    
    # User pages
	url(r'^(\w+)/$', user_page), # Main User Page
    url(r'^(\w+)/followers/$', user_followers, name='user_followers'), # user's followers page
    url(r'^(\w+)/following/$', user_following, name='user_following'), # user's following page
    url(r'^(\w+)/collegefollowing/$', user_college_following, name='user_college_following'), # user's college following page
    url(r'^(\w+)/festfollowing/$', user_fest_following, name='user_fest_following'),# user's fest following page
)

festjanta/fest/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
#from django.core.files import File
#from string import join
#from tempfile import NamedTemporaryFile
import os
#from os.path import join as pjoin
#from FestJanta.settings import MEDIA_ROOT
from django.utils.text import slugify

from django.contrib.contenttypes import generic
from django.template.loader import render_to_string
#from django.db.models import signals

from django.contrib.contenttypes.models import ContentType

#import re
from django.db.models.signals import post_save, post_delete  
from PIL import Image
from cStringIO import StringIO
from django.core.files.uploadedfile import SimpleUploadedFile
import math
from django.utils import timezone


class College(models.Model):
    name = models.CharField(unique=True, max_length=50, 
        help_text='Name of the college.'
    )
    slug = models.SlugField(unique=True)
    pub_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank = True)
    image = models.ImageField(upload_to='site-media/media/collegeimages/', 
        default = 'site-media/college_default.jpeg' 
    )
    user = models.ForeignKey(User)
    website = models.URLField(blank = True)
    location = models.CharField(max_length=50, blank = True)
    thumbnail = models.ImageField(upload_to="site-media/media/collegeimages/collegethumbs/", default = 'site-media/college_default_big.jpeg')
    thumbnail2 = models.ImageField(upload_to="site-media/media/collegeimages/collegethumbs2/", default = 'site-media/college_default_small.jpeg')

    class Meta:
        verbose_name_plural = 'Colleges'

    def get_absolute_url(self):
        return "/college/%s/" % self.slug

    def __unicode__(self):
        return self.image.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(College, self).save(*args, **kwargs)

class Fest(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank = True)
    user = models.ForeignKey(User)
    college = models.ForeignKey(College)
    pub_date = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='site-media/media/festimages/', 
        default = 'site-media/fest_default.jpeg' 
    )
    rank = models.DecimalField(default = 0, max_digits=11, decimal_places=2)
    website = models.URLField(blank = True)
    thumbnail = models.ImageField(upload_to="site-media/media/festimages/festthumbs/", default = 'site-media/fest_default_big.jpeg')
    thumbnail2 = models.ImageField(upload_to="site-media/media/festimages/festthumbs2/", default = 'site-media/fest_default_small.jpeg')

    def __unicode__(self):
        return self.image.name

    def get_absolute_url(self):
        return "/fest/%s/" % (self.slug)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.college.name) + '-' + slugify(self.name)
        super(Fest, self).save(*args, **kwargs)

    def fest_rank(self, following, time, *args):
        now = timezone.now()
        if type(time) is int:
            diff = now - datetime.fromtimestamp(time)
        else:
            diff = now - time
        second_diff = diff.seconds
        rank = following/((second_diff+2)**(1.5))
        count = 0
        rank_sum = 0
        for vals in args:
            rank_sum += vals
            count +=1
        avg_rank = rank_sum/count
        return rank + float(avg_rank)

from datetime import datetime
epoch = datetime(1970, 1, 1)
def epoch_seconds(date):
    """Returns the number of seconds from the epoch to date."""
    td = date - epoch
    return td.days * 86400 + td.seconds + (float(td.microseconds) / 1000000)

def score(ups, downs):
    return ups - downs
class Event(models.Model):
    description = models.TextField(blank = True)
    fest = models.ForeignKey(Fest)
    pub_date = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User)
    rank = models.DecimalField(default = 0, max_digits=3, decimal_places=2)

    def __unicode__(self):
        return self.description

    def fest_(self):
        return self.fest.name

    def upvotes_(self):
        return self.upvote_set.count()

    def downvotes_(self):
        return self.downvote_set.count()

    def post_rank(self, time, upvotes, downvotes):
        now = timezone.now()
        if type(time) is int:
            diff = now - datetime.fromtimestamp(time)
        else:
            diff = now - time
        second_diff = diff.seconds
        x= upvotes - downvotes
        if x>0:
            y = 1
        elif x==0:
            y = 0
        else:
            y = -1
        if abs(x)>=1:
            z = abs(x)
        else:
            z =1
        return math.log10(z) + ((y*second_diff)/45000)

    def hot(ups, downs, date):
        """The hot formula. Should match the equivalent function in postgres."""
        s = score(ups, downs)
        order = math.log(max(abs(s), 1), 10)
        sign = 1 if s > 0 else -1 if s < 0 else 0
        seconds = epoch_seconds(date) - 1134028003
        return round(order + sign * seconds / 45000, 7)

class Photo(models.Model):
    image = models.ImageField(upload_to='site-media/media/images/')
    thumbnail = models.ImageField(upload_to="site-media/media/images/thumbs/", blank=True, null=True)
    thumbnail2 = models.ImageField(upload_to="site-media/media/images/thumbs2/", blank=True, null=True)
    album = models.ForeignKey(Event)

    def create_thumbnail(self):
        # If there is no image associated with this.
         # do not create thumbnail
        if not self.image:
             return

        # Set our max thumbnail size in a tuple (max width, max height)
        THUMBNAIL_SIZE = (225,225)
        THUMBNAIL2_SIZE = (450,450)

        image = Image.open(StringIO(self.image.read()))

        
        image.thumbnail(THUMBNAIL2_SIZE, Image.ANTIALIAS)
 
        temp_handle = StringIO()
        image.save(temp_handle, 'jpeg')
        temp_handle.seek(0)
        suf = SimpleUploadedFile(os.path.split(self.image.name)[-1],
                 temp_handle.read(), content_type='jpeg')
        self.thumbnail2.save('%s_photo_thumbnail2.%s'%(os.path.splitext(suf.name)[0],'jpeg'), suf, save=False)

         # Convert to RGB if necessary
        if image.mode not in ('L', 'RGB'):
            image = image.convert('RGB')
 
         # We use our PIL Image object to create the thumbnail, which already
         # has a thumbnail() convenience method that contrains proportions.
         # Additionally, we use Image.ANTIALIAS to make the image look better.
         # Without antialiasing the image pattern artifacts may result.
        image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)
 
         # Save the thumbnail
        temp_handle = StringIO()
        image.save(temp_handle, 'jpeg')
        temp_handle.seek(0)
 
         # Save image to a SimpleUploadedFile which can be saved into
         # ImageField
        suf = SimpleUploadedFile(os.path.split(self.image.name)[-1],
                 temp_handle.read(), content_type='jpeg')
         # Save SimpleUploadedFile into image field
        self.thumbnail.save('%s_photo_thumbnail.%s'%(os.path.splitext(suf.name)[0],'jpeg'), suf, save=False)

        

    def save(self, force_insert=False, force_update=False, **kwargs):
        """Save image dimensions."""
        super(Photo, self).save(force_insert, force_update, **kwargs)

        self.create_thumbnail()
        force_insert = False
        force_update = True

        super(Photo, self).save(force_insert, force_update, **kwargs)


    def __unicode__(self):
        return self.image.name

    def album_pk_(self):
        return self.album.pk

class Upvote(models.Model):
    user = models.ForeignKey(User)
    event = models.ForeignKey(Event)
    pub_date = models.DateTimeField(default=timezone.now)

    def event_(self):
        return self.event.pk

class Downvote(models.Model):
    user = models.ForeignKey(User)
    event = models.ForeignKey(Event)
    pub_date = models.DateTimeField(default=timezone.now)

    def event_(self):
        return self.event.pk

class Comment(models.Model):
    content = models.CharField(max_length = 200)
    event = models.ForeignKey(Event)
    user = models.ForeignKey(User)
    pub_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pub_date']


class FestFollowing(models.Model):
    user = models.ForeignKey(User)
    follows = models.ForeignKey(Fest)
    pub_date = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('user', 'follows')

    def follows_(self):
        return self.follows.name

    def __unicode__(self):
        return self.follows.name

    
class CollegeFollowing(models.Model):
    user = models.ForeignKey(User)
    follows = models.ForeignKey(College)
    pub_date = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ('user', 'follows')

    def follows_(self):
        return self.follows.name

    def __unicode__(self):
        return self.follows.name


class UserFollowing(models.Model):
    user = models.OneToOneField(User)
    follows = models.ManyToManyField('self', related_name='followed_by', symmetrical=False)
    pub_date = models.DateTimeField(default=timezone.now)

    def __unicode__(self):
        return self.user.username

User.profile = property(lambda u: UserFollowing.objects.get_or_create(user=u)[0])



class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="person")
    image = models.ImageField(upload_to='site-media/media/userimages/', default = 'site-media/user_default.jpeg')
    thumbnail = models.ImageField(upload_to="site-media/media/userimages/userthumbs/", default = 'site-media/user_default_big.jpeg')

festjanta/templates/college_page.html
{% extends "base.html" %}
{% block title %}{{ college.name|title }}{% endblock %}
{% block content %}
<div class="college-container">
<div class="college-left-pane">
{% if editable %} 

<div id="edit-picture-dialog">
  <div class="dialog-title">Edit College Photo</div><!-- .dialog-title ends -->
  <input type="hidden" name="college-id" value="{{ college.id }}">
  <img class="dialog-image-thumb" src="/site-media/{{ college.thumbnail }}" height="70" width="70" />
  {% csrf_token %}
  Upload New Photo
  <input id="edit_college_image" name="image" type="file" />
  <div id="dp" class="preloader1">
      <img src="/site-media/static/images/preloader.gif" alt="Loading..." />
  </div>
  <br>
  <a id="close-dialog" href="#">Close</a>
</div><!-- #edit-picture-dialog ends -->
<div class="college">
  <div class="fest-left">
  <div class="viewp">
    <a href="#" id="edit-picture">
        <span class="dark-background">Edit Photo</span>
    </a>
    <img id="college-image" src="/site-media/{{ college.image }}" width="250" height="193" />
  </div><!-- .viewp ends -->
{% else %}

  <div class="college">
    <div class="fest-left">
  <img id="college-image" src="/site-media/{{ college.image }}" width="250" height="193" />
{% endif %}
</div><!-- .fest-left ends -->

      {% if user.is_authenticated %}
      <div class="college-right">

      {% if follows %}
        <a href="/#" cid="{{ college.id }}" id="follow-college" class="u-unfollow">Unfollow</a> 
      {% else %}
        <a href="/#" cid="{{ college.id }}" id="follow-college" class="u-follow">Follow</a>
      {% endif %}
      
      <a href="{% url 'college_followers' college.slug %}"><div class="college-followings">
        <div class="college-followings-count">{{ college_followings }}</div><!-- .fest-followings-count ends -->
        <i class="fi-torsos-all-female size-14"></i>
      </div><!-- .fest-followings ends --></a>
      </div><!-- .college-right ends -->
      {% endif %}
      <div class="college-name">{{ college.name|title }}</div><!-- .college-name ends -->
      {% csrf_token %}
      <div class="college-website"><a href="{{ college.website }}">{{ college.website|slice:"42" }}</a></div><!-- .college-website ends -->
      <div class="college-location" title="Address">{{ college.location|linebreaksbr }}</div><!-- .college-location ends -->

      
</div><!--.college-->
 
<div class="description-post">
  <div class="list-header">Description</div>
  {% if college.description %}
    <div id="add-description">
      <div class="college-description">{{ college.description|linebreaksbr }}</div><!-- .college-description ends -->
    </div><!-- #add-description ends -->
    
  {% else %}
    <div id="add-description">
      <div class="college-description">Write a <a href="/settings/college/{{ college.slug}}">description</a> about the college.</div><!-- #add-description ends -->
      </div><!-- .college-description ends -->
  {% endif %}
</div><!-- .description-post ends -->
    
</div><!-- .college-left-pane ends -->
  <div class="college-right-pane">

    <div class="college-right-pane2">
      <div class="list-header">
        Fest Trends
      </div>
      {% for fest in trends%}
        <div class="trend">
          <a href="{{ fest.get_absolute_url }}" class="trend-fest" title="{{ fest.name }}"><img class="trend-image" src="/site-media/{{ fest.thumbnail2 }}" /></a>
          <a href="{{ fest.get_absolute_url }}" class="trend-fest">{{ fest.name }}</a>
          <a href="{{ fest.college.get_absolute_url }}" class="trend-college">{{ fest.college.name }}</a>
        </div>
      {% endfor %}
    </div><!-- .home-right-pane2 ends -->
    
    <div class="college-right-pane2">
    <div class="list-header">Fests happening at {{ college.name }}</div>
    {% for fest in fests %}
    <div class="college-fest-list-fest">
    {% if user.is_authenticated %}
      {% if fest.pk in fest_followings %}  
        <a href="/#" fid="{{ fest.id }}" class="u-fest-unfollow">Unfollow</a>
      {% else %}
        <a href="/#" fid="{{ fest.id }}" class="u-fest-follow">Follow</a> 
      {% endif %}
    {% endif %}
      <img class="fest-image" src="/site-media/{{ fest.thumbnail }}" width="42" height="42" /> 
        <a href="{{ fest.get_absolute_url }}" class="fest-name-small">{{ fest.name }}</a>
        <a href="{% url 'fest_followers' fest.slug %}" class="college-fest-list-followers-count" title="Followers">{{ fest.festfollowing_set.count }}</a>
    </div><!-- .college-fest-list-fest ends -->
    {% endfor %}
  </div><!-- .college-right-pane2 ends -->



  </div><!-- .college-right-pane ends -->
</div><!-- .college-container ends -->
{% endblock %}

festjanta/templates/event_page.html
{% extends "base.html" %}
{% block title %}

    {% if event.description %}
      {{ event.description|slice:"30" }}...
    {% else %} 
      No title
    {% endif %}
{% endblock %}
{% block content %}
 {% load fest_extras %}
 <div class="event-separate-post">
<div class="event-container">
  <div class="fest-content">
  <div class="fest-content-event">
      <img class="fest-image" src="/site-media/{{ event.fest.thumbnail2 }}" />
    <a href="{{ event.fest.get_absolute_url }}" class="event-username">{{ event.fest.name }}</a>
    <div class="u-timestamp" title="{{ event.pub_date }}"><i class="fi-clock size-14"></i> {{ event.pub_date|get_date_string }}</div><!-- .u-timestamp --> 
    <div class="fest-content-event-content">
      {% with photos=event.photo_set.all %}
      {% if photos %}
        <div class="fest-content-event-content-title">
          <div class="photo-count">{{ event.photo_set.count }} <i class="fi-photo size-10"></i></div>
        </div><!-- .fest-content-event-content-title ends -->
      {% endif %}
        {% if event.description %}
          {{ event.description|linebreaksbr }}<br>
        {% endif %}
        
        {% if photos|length > 1 %}
          {% for photo in photos|slice:"2" %}
            <a href="/site-media/{{ photo.image }}" title="{{ photo.title }}" class="album-group"><img class="fest-content-event-content-photothumb" src="/site-media/{{ photo.thumbnail }}" /></a>
          {% endfor %}
          {% for photo in photos|slice:"2:" %}
              <a href="/site-media/{{ photo.image }}" title="{{ photo.title }}" class="album-group" style="display: none;"></a>
            {% endfor %}
        {% else %}
          {% for photo in photos|slice:"1" %}
            <a href="/site-media/{{ photo.image }}" class="album-group"><img class="fest-content-event-content-photo" src="/site-media/{{ photo.thumbnail2 }}" /></a>
          {% endfor %}
        {% endif %}
        {% endwith %}
    </div><!-- .fest-content-event-content ends -->
    <div class="ld-container2">
      <i class="fi-comments size-18 comment-count"></i><div class="u-comments"> {{ comments.count }} </div>
      {% with upvotes=event.upvote_set.count %}
      {% if upvoted %}
        <a href="/#" eventi="{{ event.id }}" class="u-liked"><i class="fi-like size-18"></i></a>
        <div class="u-upvotes"> {{ upvotes }} </div>
      {% else %}
        <a href="/#" eventi="{{ event.id }}" class="u-like"><i class="fi-like size-18"></i></a>
        <div class="u-upvotes"> {{ upvotes }} </div>
      {% endif %}
      {% with downvotes=event.downvote_set.count %}
      {% if downvoted %}
        <a href="/#" eventi="{{ event.id }}" class="u-disliked"><i class="fi-dislike size-18"></i></a>
        <div class="u-downvotes"> {{ downvotes }} </div>
      {% else %}
        <a href="/#" eventi="{{ event.id }}" class="u-dislike"><i class="fi-dislike size-18"></i></a>
        <div class="u-downvotes"> {{ downvotes }} </div> 
      {% endif %}
      
      
      
      
      
    </div>
    <div class="countbar">
      <div class="countbar-like"></div>
      <div class="countbar-dislike"></div>
      <div class="ups">{{ upvotes }}</div><!-- .ups ends -->
      <div class="downs">{{ downvotes }}</div><!-- .downs ends -->
      {% endwith %}
      {% endwith %}
    </div>
    {% if user.is_authenticated %}
    <div class="fest-content-event-comment-post">
      <img class="fest-image" src="/site-media/{{ user.person.thumbnail2 }}" />
      <form method="post">
        {% csrf_token %}
        <textarea class="comment-post-content" name="comment-post-content" cols="55" rows="1" placeholder="Add a comment..."></textarea>
        <input type="hidden" class="event-id" value="{{ event.id }}">
        <input type="submit" class="u-post-button" value="Post comment" />
      </form>

    </div><!-- .fest-content-event-comment-post --> 
    {% endif %}         
      <div class="fest-content-event-comment">
        <div class="latest-comment"></div>
        {% include page_template %}
      </div><!-- .fest-content-event-comment ends -->  
  </div><!-- .fest-content-event-->
  </div><!-- .fest-content ends -->

  {% endblock %}
</div><!-- .event-container ends -->
</div>

festjanta/templates/event_page_part.html
{% load endless %}
{% load fest_extras %}
{% lazy_paginate comments %}

{% for comment in comments %}
    <img class="fest-image" src="/site-media/{{ comment.user.person.thumbnail2 }}" />
    <a href="/{{ comment.user.username }}/" class="first_name">{{ comment.user.first_name }}</a><br /> 
    <div class="u-timestamp" title="{{ comment.pub_date }}" >{{ comment.pub_date|get_date_string }}</div><!-- .u-timestamp -->
    <div class="fest-content-event-content-comment"> 
        {{ comment.content|linebreaksbr }}
    </div><!-- .fest-content-event-content ends -->
{% endfor %}

{% show_more %}

festjanta/templates/fest_following.html
{% extends "base.html" %}
{% block title %}{{ fest.name }} - {{ fest.college.name|title }}{% endblock %}
{% block content %}
<div class="fest-container">
<div class="fest-left-pane">

{% csrf_token %}
{% if editable %} 
<div id="edit-picture-dialog">
  <div class="dialog-title">Edit Profile Photo</div><!-- .dialog-title ends -->
  <img class="dialog-image-thumb" src="/site-media/{{ fest.thumbnail }}" />
  Upload New Photo
  <input id="edit_fest_image" name="image" type="file" />
  <br>
  <a id="close-dialog" href="#">Close</a>
</div><!-- #edit-picture-dialog ends -->
<div class="fest">
  <div class="fest-left">
  <div class="viewp">
    <a href="#" id="edit-picture">
        <span class="dark-background">Edit Photo</span>
    </a>
    <img id="fest-image" src="/site-media/{{ fest.image }}" width="250" height="193" />
  </div><!-- .viewp ends -->

{% else %}
  <div class="fest">
    <div class="fest-left">
  <img id="fest-image" src="/site-media/{{ fest.image }}" width="250" height="193" />
{% endif %}
</div><!-- .fest-left ends -->

{% if user.is_authenticated %}
<div class="fest-right">

  {% if follows %}
    <a href="/#" fid = "{{ fest.id }}" id="follow-fest" class="u-unfollow">Unfollow</a>
  {% else %}
    <a href="/#" fid = "{{ fest.id }}" id="follow-fest" class="u-follow">Follow</a>
  {% endif %}
  <a href=""{% url 'fest_followers' fest.slug %}""><div class="fest-followings">
    <div class="fest-followings-count">{{ fest.festfollowing_set.count }}</div><!-- .fest-followings-count ends -->
    <i class="fi-torsos-all-female size-14"></i>
  </div><!-- .fest-followings ends --></a>
</div><!-- .fest-right ends -->
{% endif %}

   
  <a href="{{ fest.get_absolute_url }}"><div class="fest-name">{{ fest.name }}</div><!-- .fest-name ends --></a>
  <a href="{{ fest.college.get_absolute_url }}" class="fest-college-name">{{ fest.college.name|title }}</a><!-- .fest-college-name ends -->
  <div class="fest-website"><a href="{{ fest.website }}">{{ fest.website }}</a></div><!-- .fest-website ends -->
  <div class="fest-date">{{ fest.date }}</div><!-- .cfest-date ends -->
  
</div><!--.fest ends-->


<div class="fest-left-2">
  <div class="list-header">Followers - {{ fest_followers.count }}</div>
  {% include page_template %}
  
</div><!-- .fest-left-2 ends -->

</div><!-- .fest-left-pane ends -->
  <div class="fest-right-pane">
    <div class="fest-right-pane2">
  
  {% if fest.description %}
  <div class="list-header">Description</div>
    <div id="add-description">
      <div class="college-description">{{ fest.description|linebreaksbr }}</div><!-- .college-description ends -->
    </div><!-- #add-description ends -->
  {% else %}
   {% if editable %}
   <div class="list-header">Description</div>
    <div id="add-description">
      <div class="college-description">Write a <a href="/settings/fest/{{ fest.slug }}/">description</a> about the fest.</div><!-- #add-description ends -->
      </div><!-- .college-description ends -->
    {% endif %}
  {% endif %}
    </div><!-- .fest-right-pane2 ends -->
  </div><!-- .fest-right-pane ends -->
</div><!-- .fest-container ends -->
{% endblock %}

festjanta/templates/main_page_part.html
{% load endless %}

{% lazy_paginate feeds %}

{% for feed in feeds %}  
    {{ feed.get_rendered_html }}
{% endfor %}

{% show_more %}